dist: trusty
language: node_js
node_js:
- "stable"
before_script:
- npm install
script:
- npm run build
deploy:
  provider: surge
  project: ./dist/
  domain: https://kontent-sample-app-vue.surge.sh 
  skip_cleanup: true

